version: '3.8'

networks:
  laravel:

services:
  nginx-laravel-demo:
    image: nginx:1.19.0-alpine
    container_name: nginx-laravel-demo
    ports:
      - "1338:80"
    volumes:
      - ./laravel-demo:/var/www/laravel-demo
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-demo
      - db
    networks:
      - laravel

  db:
    tty: true
    image: postgres:10
    volumes:
      - ./db/:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SUPER_SECRET_PASSWORD  
    networks:
        - laravel

  laravel-demo:
    build:
      context: laravel-demo
      dockerfile: Dockerfile
    container_name: laravel-demo
    env_file:
      - ./laravel-demo/.env
    volumes:
      - ./laravel-demo:/var/www/laravel-demo
    working_dir: /var/www/laravel-demo
    depends_on:
      - db
    networks:
      - laravel
